behaviors:
  diagmazeexplo:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.015 # maybe set back to 0.005
      epsilon: 0.80 # maybe set back to 0.80
      lambd: 0.95
      num_epoch: 1
      learning_rate_schedule: linear
    network_settings:
      normalize: true # maybe set back to false
      hidden_units: 64
      num_layers: 10
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 2000000
    time_horizon: 256 # maybe set back to 64.
    summary_freq: 50000
